### ISSUE TITLE
add aerodromes

### ISSUE THREAD

**Issue by Joaobazzo** [ipeaGIT/flightsbr#4]
https://www.anac.gov.br/acesso-a-informacao/dados-abertos/areas-de-atuacao/aerodromos

**Comment by rafapereirabr** [comment]
I've created a 1st version of the function. See commit above.

**Comment by rafapereirabr** [comment]
ps. Now we can use this data to calculate distances between airports for our paper.

**Comment by rafapereirabr** [comment]
done
