### ISSUE TITLE
spelling read_aicrafts() -> read_aircraft()

### ISSUE THREAD

**Issue by espinielli** [ipeaGIT/flightsbr#45]
In English plural of aircraft is still aircraft (no final 's').
I would suggest adding `read_aircraft()` and add a deprecation for a while on `read_aircrafts()` before eliminating the mispelled one.

**Comment by rafapereirabr** [comment]
thanks for the heads ups! This is going to be implemented in the next version!

**Comment by rafapereirabr** [comment]
thanks. This is now implemented in the dev version v1.0.1.
